# Generated by Django 2.1 on 2018-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='adult_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='child_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='indications',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='interaction',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mode_of_action',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pack_size_price',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='precautions_and_worning',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pregnancy_category',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='renal_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='side_effects',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='therapeutic_class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
