# Generated by Django 2.1 on 2018-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinfo', '0002_auto_20180905_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=125)),
                ('result', models.CharField(max_length=25)),
            ],
        ),
    ]
