# Generated by Django 2.1 on 2018-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinfo', '0003_studentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='roll',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='adult_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='child_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='contraindications',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='indications',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='interaction',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='mode_of_action',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='pack_size_price',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='precautions_and_worning',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='pregnancy_category',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='renal_dose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='side_effects',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='therapeutic_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
