# Generated by Django 2.1 on 2018-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinfo', '0004_auto_20180905_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
